// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using AlbertaAdventureClassLibrary.Entities;
using Microsoft.EntityFrameworkCore;

namespace AlbertaAdventureClassLibrary.DAL;

public partial class aamcgeardbContext : DbContext
{
    public aamcgeardbContext(DbContextOptions<aamcgeardbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<GearInventory> GearInventories { get; set; }

    public virtual DbSet<Reservation> Reservations { get; set; }

    public virtual DbSet<ReservationGear> ReservationGears { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.CategoryID).HasName("PK__Categori__19093A2BB0B0080A");
        });

        modelBuilder.Entity<GearInventory>(entity =>
        {
            entity.HasKey(e => e.GearID).HasName("PK__GearInve__7117DD6C9B9B506A");

            entity.Property(e => e.IsAvailable).HasDefaultValue(true);

            entity.HasOne(d => d.Category).WithMany(p => p.GearInventories)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__GearInven__Categ__0E6E26BF");
        });

        modelBuilder.Entity<Reservation>(entity =>
        {
            entity.HasKey(e => e.ReservationID).HasName("PK__Reservat__B7EE5F041F86B390");

            entity.Property(e => e.RequestDate).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.User).WithMany(p => p.Reservations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Reservati__UserI__123EB7A3");
        });

        modelBuilder.Entity<ReservationGear>(entity =>
        {
            entity.HasKey(e => e.ReservationGearID).HasName("PK__Reservat__C2297C668D90465D");

            entity.HasOne(d => d.Gear).WithMany(p => p.ReservationGears)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Reservati__GearI__160F4887");

            entity.HasOne(d => d.Reservation).WithMany(p => p.ReservationGears)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Reservati__Reser__151B244E");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserID).HasName("PK__Users__1788CCAC75CF8F34");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}