// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AlbertaAdventureClassLibrary.Entities;

[Index("CategoryName", Name = "UQ__Categori__8517B2E06C5B1F5C", IsUnique = true)]
public partial class Category
{
    [Key]
    public int CategoryID { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string CategoryName { get; set; }

    [InverseProperty("Category")]
    public virtual ICollection<GearInventory> GearInventories { get; set; } = new List<GearInventory>();
}