// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AlbertaAdventureClassLibrary.Entities;

[Table("GearInventory")]
[Index("TagNumber", Name = "UQ__GearInve__7EE688E4B4AC1295", IsUnique = true)]
public partial class GearInventory
{
    [Key]
    public int GearID { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string TagNumber { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string Picture { get; set; }

    public int CategoryID { get; set; }

    [Required]
    [Column(TypeName = "text")]
    public string Description { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Brand { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Size { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Condition { get; set; }

    public int HoursUsed { get; set; }

    public int? HoursLimit { get; set; }

    public bool? IsAvailable { get; set; }

    [ForeignKey("CategoryID")]
    [InverseProperty("GearInventories")]
    public virtual Category Category { get; set; }

    [InverseProperty("Gear")]
    public virtual ICollection<ReservationGear> ReservationGears { get; set; } = new List<ReservationGear>();
}