// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AlbertaAdventureClassLibrary.Entities;

[Table("ReservationGear")]
public partial class ReservationGear
{
    [Key]
    public int ReservationGearID { get; set; }

    public int ReservationID { get; set; }

    public int GearID { get; set; }

    [ForeignKey("GearID")]
    [InverseProperty("ReservationGears")]
    public virtual GearInventory Gear { get; set; }

    [ForeignKey("ReservationID")]
    [InverseProperty("ReservationGears")]
    public virtual Reservation Reservation { get; set; }
}